"""Creates the read-only Kubernetes identity the AI platform authenticates with.

The platform runs in Docker Compose, outside the cluster, so it cannot use the
service account token that Kubernetes projects into a pod. Instead this module
applies the RBAC manifests, reads the token Kubernetes minted for the
kubesage-observer service account, and writes a kubeconfig the platform
container can mount.

Two details in the generated kubeconfig matter:

  * the server address is host.docker.internal, not a Kind node IP. Node
    addresses change on every cluster recreate and are not routable from the
    Compose network;

  * the cluster CA certificate is embedded, and TLS verification stays ON.
    The Kind cluster is configured with host.docker.internal in the API
    server certificate's subject alternative names precisely so that this
    works without disabling verification.

The generated file contains a real credential. It is written to a directory
that .gitignore excludes and mounted into the container read-only.
"""

from __future__ import annotations

import base64
import json

from . import cluster, shell
from .config import COMPOSE_GENERATED_DIR, K8S_DIR, Settings

RBAC_MANIFESTS = K8S_DIR / "rbac"
SERVICE_ACCOUNT = "kubesage-observer"
TOKEN_SECRET = "kubesage-observer-token"
OBSERVER_NAMESPACE = "kubesage-observability"

KUBECONFIG_FILE = COMPOSE_GENERATED_DIR / "kubeconfig.yaml"


def apply_rbac(settings: Settings) -> None:
    shell.step("Applying read-only Kubernetes RBAC for the platform")
    cluster.apply_manifests(settings, str(RBAC_MANIFESTS))
    shell.ok("kubesage-observer service account and roles applied")


def _read_secret_field(settings: Settings, field: str) -> str:
    """Read one base64 field out of the service account token Secret."""
    data = cluster.kubectl_json(
        settings, "get", "secret", TOKEN_SECRET, "-n", OBSERVER_NAMESPACE
    )
    value = data.get("data", {}).get(field)

    if not value:
        raise RuntimeError(
            f"Secret {TOKEN_SECRET} has no '{field}' yet. "
            "Kubernetes populates it a moment after the secret is created; retry shortly."
        )

    return base64.b64decode(value).decode("utf-8")


def generate_kubeconfig(settings: Settings) -> str:
    """Write the kubeconfig the platform container mounts."""
    shell.step("Generating the platform's read-only kubeconfig")

    def token_ready() -> bool:
        try:
            _read_secret_field(settings, "token")
            return True
        except Exception:
            return False

    if not shell.wait_until("service account token to be issued", token_ready, timeout=60, interval=2):
        raise RuntimeError("Kubernetes did not issue a token for the kubesage-observer service account.")

    token = _read_secret_field(settings, "token")
    ca_certificate = _read_secret_field(settings, "ca.crt")
    ca_base64 = base64.b64encode(ca_certificate.encode("utf-8")).decode("ascii")

    server = f"https://host.docker.internal:{settings.port('KIND_API_HOST_PORT')}"

    kubeconfig = f"""# Generated by `python kubesage.py bootstrap`. Do not edit or commit.
#
# Credentials for the read-only kubesage-observer service account. This
# identity can read pods, events, deployments and logs in the two KubeSage
# namespaces, and can change nothing anywhere.
apiVersion: v1
kind: Config
clusters:
  - name: kubesage
    cluster:
      server: {server}
      certificate-authority-data: {ca_base64}
contexts:
  - name: kubesage-observer
    context:
      cluster: kubesage
      user: kubesage-observer
      namespace: {settings.workload_namespace}
current-context: kubesage-observer
users:
  - name: kubesage-observer
    user:
      token: {token}
"""

    COMPOSE_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    KUBECONFIG_FILE.write_text(kubeconfig, encoding="utf-8")

    shell.ok(f"wrote {KUBECONFIG_FILE.name} pointing at {server}")
    return str(KUBECONFIG_FILE)


def verify_read_only(settings: Settings) -> tuple[bool, list[str]]:
    """Prove the observer identity really cannot change anything.

    This asks the Kubernetes API server itself, with `kubectl auth can-i`,
    rather than trying to reason about the RBAC rules. The API server is the
    component that will actually make the decision at runtime, so its answer
    is the only one that counts.
    """
    account = f"system:serviceaccount:{OBSERVER_NAMESPACE}:{SERVICE_ACCOUNT}"
    problems: list[str] = []

    # Must be allowed: the reads an investigation depends on.
    allowed = [
        ("get", "pods", settings.workload_namespace),
        ("list", "pods", settings.workload_namespace),
        ("get", "pods/log", settings.workload_namespace),
        ("list", "events", settings.workload_namespace),
        ("list", "deployments.apps", settings.workload_namespace),
    ]

    # Must be denied: anything that changes the cluster, reads credentials,
    # or opens a way into a container.
    denied = [
        ("delete", "pods", settings.workload_namespace),
        ("create", "pods", settings.workload_namespace),
        ("patch", "deployments.apps", settings.workload_namespace),
        ("update", "deployments.apps", settings.workload_namespace),
        ("delete", "deployments.apps", settings.workload_namespace),
        ("get", "secrets", settings.workload_namespace),
        ("list", "secrets", settings.workload_namespace),
        ("create", "pods/exec", settings.workload_namespace),
        ("create", "pods/portforward", settings.workload_namespace),
        ("patch", "nodes", ""),
    ]

    for verb, resource, namespace in allowed:
        args = ["auth", "can-i", verb, resource, f"--as={account}"]
        if namespace:
            args += ["-n", namespace]
        result = cluster.kubectl(settings, *args, check=False)
        if result.stdout.strip() != "yes":
            problems.append(f"should be ALLOWED but is not: {verb} {resource}")

    for verb, resource, namespace in denied:
        args = ["auth", "can-i", verb, resource, f"--as={account}"]
        if namespace:
            args += ["-n", namespace]
        result = cluster.kubectl(settings, *args, check=False)
        if result.stdout.strip() != "no":
            problems.append(f"should be DENIED but is allowed: {verb} {resource}")

    return not problems, problems
